"""Curated built-in mock anime dataset for testing and offline fallbacks."""

from __future__ import annotations
from typing import Any, Dict, List

MOCK_ANIME_DATA: List[Dict[str, Any]] = [
    # 1. Classics
    {
        "id": 30,
        "title": {
            "romaji": "Shinseiki Evangelion",
            "english": "Neon Genesis Evangelion",
        },
        "seasonYear": 1995,
        "season": "FALL",
        "episodes": 26,
        "duration": 24,
        "genres": ["Action", "Drama", "Mecha", "Mystery", "Psychological", "Sci-Fi"],
        "tags": [
            {"name": "Philosophy", "rank": 96, "isMediaSpoiler": False},
            {"name": "Post-Apocalyptic", "rank": 90, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "Gainax", "isAnimationStudio": True}]},
        "source": "ORIGINAL",
        "averageScore": 83,
        "popularity": 285400,
        "favourites": 32400,
    },
    {
        "id": 1,
        "title": {"romaji": "Cowboy Bebop", "english": "Cowboy Bebop"},
        "seasonYear": 1998,
        "season": "SPRING",
        "episodes": 26,
        "duration": 24,
        "genres": ["Action", "Adventure", "Drama", "Sci-Fi"],
        "tags": [
            {"name": "Space", "rank": 95, "isMediaSpoiler": False},
            {"name": "Bounty Hunter", "rank": 93, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "Sunrise", "isAnimationStudio": True}]},
        "source": "ORIGINAL",
        "averageScore": 86,
        "popularity": 320100,
        "favourites": 38900,
    },
    {
        "id": 164,
        "title": {"romaji": "Mononoke Hime", "english": "Princess Mononoke"},
        "seasonYear": 1997,
        "season": "SUMMER",
        "episodes": 1,
        "duration": 133,
        "genres": ["Action", "Adventure", "Drama", "Fantasy"],
        "tags": [
            {"name": "Environmental", "rank": 97, "isMediaSpoiler": False},
            {"name": "Historical", "rank": 91, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "Studio Ghibli", "isAnimationStudio": True}]},
        "source": "ORIGINAL",
        "averageScore": 88,
        "popularity": 235000,
        "favourites": 19200,
    },
    {
        "id": 6,
        "title": {"romaji": "Trigun", "english": "Trigun"},
        "seasonYear": 1998,
        "season": "SPRING",
        "episodes": 26,
        "duration": 24,
        "genres": ["Action", "Adventure", "Comedy", "Drama", "Sci-Fi"],
        "tags": [
            {"name": "Post-Apocalyptic", "rank": 91, "isMediaSpoiler": False},
            {"name": "Guns", "rank": 93, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "Madhouse", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 79,
        "popularity": 142000,
        "favourites": 8900,
    },
    {
        "id": 43,
        "title": {"romaji": "Koukaku Kidoutai", "english": "Ghost in the Shell"},
        "seasonYear": 1995,
        "season": "FALL",
        "episodes": 1,
        "duration": 82,
        "genres": ["Action", "Psychological", "Sci-Fi"],
        "tags": [
            {"name": "Cyberpunk", "rank": 98, "isMediaSpoiler": False},
            {"name": "Philosophy", "rank": 94, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "Production I.G", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 81,
        "popularity": 178000,
        "favourites": 12100,
    },
    {
        "id": 47,
        "title": {"romaji": "AKIRA", "english": "Akira"},
        "seasonYear": 1988,
        "season": "SUMMER",
        "episodes": 1,
        "duration": 124,
        "genres": ["Action", "Adventure", "Sci-Fi", "Supernatural"],
        "tags": [
            {"name": "Cyberpunk", "rank": 97, "isMediaSpoiler": False},
            {"name": "Dystopian", "rank": 93, "isMediaSpoiler": False},
        ],
        "studios": {
            "nodes": [{"name": "Tokyo Movie Shinsha", "isAnimationStudio": True}]
        },
        "source": "MANGA",
        "averageScore": 79,
        "popularity": 192000,
        "favourites": 14300,
    },
    {
        "id": 33,
        "title": {"romaji": "Kenpuu Denki Berserk", "english": "Berserk"},
        "seasonYear": 1997,
        "season": "FALL",
        "episodes": 25,
        "duration": 24,
        "genres": ["Action", "Adventure", "Drama", "Fantasy", "Horror"],
        "tags": [
            {"name": "Dark Fantasy", "rank": 98, "isMediaSpoiler": False},
            {"name": "Gore", "rank": 94, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "OLM", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 85,
        "popularity": 184000,
        "favourites": 22100,
    },
    {
        "id": 5114,
        "title": {
            "romaji": "Fullmetal Alchemist: Brotherhood",
            "english": "Fullmetal Alchemist: Brotherhood",
        },
        "seasonYear": 2009,
        "season": "SPRING",
        "episodes": 64,
        "duration": 24,
        "genres": ["Action", "Adventure", "Drama", "Fantasy"],
        "tags": [
            {"name": "Military", "rank": 98, "isMediaSpoiler": False},
            {"name": "Alchemy", "rank": 98, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "Bones", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 90,
        "popularity": 520000,
        "favourites": 65000,
    },
    # 2. Modern Hits
    {
        "id": 101922,
        "title": {
            "romaji": "Kimetsu no Yaiba",
            "english": "Demon Slayer: Kimetsu no Yaiba",
        },
        "seasonYear": 2019,
        "season": "SPRING",
        "episodes": 26,
        "duration": 23,
        "genres": ["Action", "Adventure", "Drama", "Fantasy", "Supernatural"],
        "tags": [
            {"name": "Demons", "rank": 97, "isMediaSpoiler": False},
            {"name": "Swordplay", "rank": 95, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "ufotable", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 84,
        "popularity": 648000,
        "favourites": 71200,
    },
    {
        "id": 113415,
        "title": {"romaji": "Jujutsu Kaisen", "english": "Jujutsu Kaisen"},
        "seasonYear": 2020,
        "season": "FALL",
        "episodes": 24,
        "duration": 24,
        "genres": ["Action", "Drama", "Supernatural"],
        "tags": [
            {"name": "Curse", "rank": 96, "isMediaSpoiler": False},
            {"name": "Shounen", "rank": 95, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "MAPPA", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 85,
        "popularity": 592000,
        "favourites": 68400,
    },
    {
        "id": 154587,
        "title": {
            "romaji": "Sousou no Frieren",
            "english": "Frieren: Beyond Journey's End",
        },
        "seasonYear": 2023,
        "season": "FALL",
        "episodes": 28,
        "duration": 24,
        "genres": ["Adventure", "Drama", "Fantasy"],
        "tags": [
            {"name": "Magic", "rank": 98, "isMediaSpoiler": False},
            {"name": "Elf", "rank": 96, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "Madhouse", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 92,
        "popularity": 320000,
        "favourites": 45100,
    },
    {
        "id": 127230,
        "title": {"romaji": "Chainsaw Man", "english": "Chainsaw Man"},
        "seasonYear": 2022,
        "season": "FALL",
        "episodes": 12,
        "duration": 24,
        "genres": ["Action", "Drama", "Horror", "Supernatural"],
        "tags": [
            {"name": "Gore", "rank": 96, "isMediaSpoiler": False},
            {"name": "Demons", "rank": 95, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "MAPPA", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 84,
        "popularity": 460000,
        "favourites": 48900,
    },
    {
        "id": 140960,
        "title": {"romaji": "SPY×FAMILY", "english": "SPY x FAMILY"},
        "seasonYear": 2022,
        "season": "SPRING",
        "episodes": 12,
        "duration": 24,
        "genres": ["Action", "Comedy", "Slice of Life", "Supernatural"],
        "tags": [
            {"name": "Espionage", "rank": 96, "isMediaSpoiler": False},
            {"name": "Family Life", "rank": 95, "isMediaSpoiler": False},
        ],
        "studios": {
            "nodes": [
                {"name": "WIT Studio", "isAnimationStudio": True},
                {"name": "CloverWorks", "isAnimationStudio": True},
            ]
        },
        "source": "MANGA",
        "averageScore": 83,
        "popularity": 420000,
        "favourites": 31500,
    },
    # 3. Cult Favorites
    {
        "id": 7785,
        "title": {"romaji": "Yojouhan Shinwa Taikei", "english": "The Tatami Galaxy"},
        "seasonYear": 2010,
        "season": "SPRING",
        "episodes": 11,
        "duration": 23,
        "genres": ["Comedy", "Mystery", "Psychological", "Romance"],
        "tags": [
            {"name": "Time Loop", "rank": 96, "isMediaSpoiler": False},
            {"name": "Surreal", "rank": 94, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "Madhouse", "isAnimationStudio": True}]},
        "source": "NOVEL",
        "averageScore": 85,
        "popularity": 132000,
        "favourites": 16400,
    },
    {
        "id": 5081,
        "title": {"romaji": "Bakemonogatari", "english": "Bakemonogatari"},
        "seasonYear": 2009,
        "season": "SUMMER",
        "episodes": 15,
        "duration": 25,
        "genres": [
            "Comedy",
            "Drama",
            "Mystery",
            "Psychological",
            "Romance",
            "Supernatural",
        ],
        "tags": [
            {"name": "Dialogue-Driven", "rank": 98, "isMediaSpoiler": False},
            {"name": "Avant Garde", "rank": 90, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "Shaft", "isAnimationStudio": True}]},
        "source": "LIGHT_NOVEL",
        "averageScore": 83,
        "popularity": 298000,
        "favourites": 39800,
    },
    {
        "id": 19,
        "title": {"romaji": "MONSTER", "english": "Monster"},
        "seasonYear": 2004,
        "season": "SPRING",
        "episodes": 74,
        "duration": 24,
        "genres": ["Drama", "Mystery", "Psychological", "Thriller"],
        "tags": [
            {"name": "Serial Killer", "rank": 98, "isMediaSpoiler": False},
            {"name": "Medical", "rank": 92, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "Madhouse", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 88,
        "popularity": 265000,
        "favourites": 37200,
    },
    # 4. Low-Profile
    {
        "id": 2294,
        "title": {
            "romaji": "Sousei Kishi Gaiarth",
            "english": "Genesis Survivor Gaiarth",
        },
        "seasonYear": 1992,
        "season": "SPRING",
        "episodes": 3,
        "duration": 48,
        "genres": ["Action", "Adventure", "Sci-Fi"],
        "tags": [{"name": "Cyborg", "rank": 70, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "AIC", "isAnimationStudio": True}]},
        "source": "ORIGINAL",
        "averageScore": 62,
        "popularity": 2400,
        "favourites": 28,
    },
    {
        "id": 21188,
        "title": {"romaji": "Vampire Holmes", "english": "Vampire Holmes"},
        "seasonYear": 2015,
        "season": "SPRING",
        "episodes": 12,
        "duration": 3,
        "genres": ["Comedy", "Mystery", "Supernatural"],
        "tags": [{"name": "Detective", "rank": 60, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "Studio! Cucuri", "isAnimationStudio": True}]},
        "source": "VIDEO_GAME",
        "averageScore": 34,
        "popularity": 5400,
        "favourites": 38,
    },
    # 5. Niche / Experimental
    {
        "id": 885,
        "title": {"romaji": "Tenshi no Tamago", "english": "Angel's Egg"},
        "seasonYear": 1985,
        "season": "FALL",
        "episodes": 1,
        "duration": 71,
        "genres": ["Drama", "Fantasy", "Psychological"],
        "tags": [
            {"name": "Avant Garde", "rank": 98, "isMediaSpoiler": False},
            {"name": "Surreal", "rank": 96, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "Studio Deen", "isAnimationStudio": True}]},
        "source": "ORIGINAL",
        "averageScore": 77,
        "popularity": 54000,
        "favourites": 6800,
    },
    {
        "id": 227,
        "title": {"romaji": "FLCL", "english": "FLCL"},
        "seasonYear": 2000,
        "season": "SPRING",
        "episodes": 6,
        "duration": 25,
        "genres": ["Action", "Comedy", "Mecha", "Sci-Fi"],
        "tags": [
            {"name": "Surreal", "rank": 96, "isMediaSpoiler": False},
            {"name": "Rock Music", "rank": 94, "isMediaSpoiler": False},
        ],
        "studios": {"nodes": [{"name": "Gainax", "isAnimationStudio": True}]},
        "source": "ORIGINAL",
        "averageScore": 80,
        "popularity": 195000,
        "favourites": 22300,
    },
    {
        "id": 9253,
        "title": {"romaji": "Steins;Gate", "english": "Steins;Gate"},
        "seasonYear": 2011,
        "season": "SPRING",
        "episodes": 24,
        "duration": 24,
        "genres": ["Drama", "Psychological", "Sci-Fi", "Thriller"],
        "tags": [{"name": "Time Travel", "rank": 99, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "White Fox", "isAnimationStudio": True}]},
        "source": "VISUAL_NOVEL",
        "averageScore": 89,
        "popularity": 490000,
        "favourites": 73200,
    },
    {
        "id": 9756,
        "title": {
            "romaji": "Mahou Shoujo Madoka☆Magica",
            "english": "Puella Magi Madoka Magica",
        },
        "seasonYear": 2011,
        "season": "WINTER",
        "episodes": 12,
        "duration": 24,
        "genres": ["Action", "Drama", "Fantasy", "Psychological", "Thriller"],
        "tags": [{"name": "Tragedy", "rank": 95, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "Shaft", "isAnimationStudio": True}]},
        "source": "ORIGINAL",
        "averageScore": 84,
        "popularity": 340000,
        "favourites": 41200,
    },
    {
        "id": 457,
        "title": {"romaji": "Mushishi", "english": "Mushishi"},
        "seasonYear": 2005,
        "season": "FALL",
        "episodes": 26,
        "duration": 25,
        "genres": ["Adventure", "Fantasy", "Mystery", "Slice of Life"],
        "tags": [{"name": "Iyashikei", "rank": 96, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "Artland", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 86,
        "popularity": 182000,
        "favourites": 21800,
    },
    {
        "id": 2001,
        "title": {"romaji": "Tengen Toppa Gurren Lagann", "english": "Gurren Lagann"},
        "seasonYear": 2007,
        "season": "SPRING",
        "episodes": 27,
        "duration": 24,
        "genres": ["Action", "Adventure", "Comedy", "Mecha", "Sci-Fi"],
        "tags": [{"name": "Super Robot", "rank": 98, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "Gainax", "isAnimationStudio": True}]},
        "source": "ORIGINAL",
        "averageScore": 85,
        "popularity": 360000,
        "favourites": 44800,
    },
    {
        "id": 20607,
        "title": {
            "romaji": "Ping Pong THE ANIMATION",
            "english": "Ping Pong the Animation",
        },
        "seasonYear": 2014,
        "season": "SPRING",
        "episodes": 11,
        "duration": 23,
        "genres": ["Drama", "Psychological", "Sports"],
        "tags": [{"name": "Stylized Art", "rank": 95, "isMediaSpoiler": False}],
        "studios": {
            "nodes": [{"name": "Tatsunoko Production", "isAnimationStudio": True}]
        },
        "source": "MANGA",
        "averageScore": 86,
        "popularity": 145000,
        "favourites": 17800,
    },
    {
        "id": 339,
        "title": {
            "romaji": "Serial Experiments Lain",
            "english": "Serial Experiments Lain",
        },
        "seasonYear": 1998,
        "season": "SUMMER",
        "episodes": 13,
        "duration": 23,
        "genres": ["Drama", "Mystery", "Psychological", "Sci-Fi"],
        "tags": [{"name": "Cyberpunk", "rank": 97, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "Triangle Staff", "isAnimationStudio": True}]},
        "source": "ORIGINAL",
        "averageScore": 80,
        "popularity": 221000,
        "favourites": 28400,
    },
    {
        "id": 2737,
        "title": {"romaji": "Dark Cat", "english": "Dark Cat"},
        "seasonYear": 1991,
        "season": "FALL",
        "episodes": 1,
        "duration": 60,
        "genres": ["Action", "Horror", "Supernatural"],
        "tags": [{"name": "Demons", "rank": 65, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "Nikkatsu", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 51,
        "popularity": 1800,
        "favourites": 12,
    },
    {
        "id": 413,
        "title": {"romaji": "Hametsu no Mars", "english": "Mars of Destruction"},
        "seasonYear": 2005,
        "season": "SUMMER",
        "episodes": 1,
        "duration": 19,
        "genres": ["Action", "Horror", "Sci-Fi"],
        "tags": [{"name": "Aliens", "rank": 60, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "Idea Factory", "isAnimationStudio": True}]},
        "source": "VIDEO_GAME",
        "averageScore": 26,
        "popularity": 9400,
        "favourites": 92,
    },
    {
        "id": 19315,
        "title": {"romaji": "Pupa", "english": "Pupa"},
        "seasonYear": 2014,
        "season": "WINTER",
        "episodes": 12,
        "duration": 4,
        "genres": ["Drama", "Fantasy", "Horror"],
        "tags": [{"name": "Cannibalism", "rank": 78, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "Studio Deen", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 45,
        "popularity": 24000,
        "favourites": 120,
    },
    {
        "id": 601,
        "title": {"romaji": "Nekojiru-sou", "english": "Cat Soup"},
        "seasonYear": 2001,
        "season": "WINTER",
        "episodes": 1,
        "duration": 32,
        "genres": ["Comedy", "Psychological"],
        "tags": [{"name": "Surreal", "rank": 98, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "J.C.Staff", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 73,
        "popularity": 48000,
        "favourites": 4300,
    },
    {
        "id": 1983,
        "title": {"romaji": "Paprika", "english": "Paprika"},
        "seasonYear": 2006,
        "season": "FALL",
        "episodes": 1,
        "duration": 90,
        "genres": ["Fantasy", "Mystery", "Psychological", "Sci-Fi"],
        "tags": [{"name": "Dreams", "rank": 99, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "Madhouse", "isAnimationStudio": True}]},
        "source": "NOVEL",
        "averageScore": 82,
        "popularity": 182000,
        "favourites": 14900,
    },
    {
        "id": 98460,
        "title": {"romaji": "DEVILMAN crybaby", "english": "Devilman Crybaby"},
        "seasonYear": 2018,
        "season": "WINTER",
        "episodes": 10,
        "duration": 25,
        "genres": ["Action", "Drama", "Horror", "Supernatural"],
        "tags": [{"name": "Demons", "rank": 98, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "Science SARU", "isAnimationStudio": True}]},
        "source": "MANGA",
        "averageScore": 78,
        "popularity": 268000,
        "favourites": 21500,
    },
    {
        "id": 132126,
        "title": {"romaji": "Sonny Boy", "english": "Sonny Boy"},
        "seasonYear": 2021,
        "season": "SUMMER",
        "episodes": 12,
        "duration": 24,
        "genres": ["Drama", "Mystery", "Psychological", "Sci-Fi"],
        "tags": [{"name": "Surreal", "rank": 96, "isMediaSpoiler": False}],
        "studios": {"nodes": [{"name": "Madhouse", "isAnimationStudio": True}]},
        "source": "ORIGINAL",
        "averageScore": 78,
        "popularity": 120000,
        "favourites": 14200,
    },
]
